var Student=[
    {
        "name":"Surya",
        "class":"4th",
        "age":"23",
        "Address":"Chittoor",
        "city":"AP"
    },
    {
        "name":"Surya",
        "class":"4th",
        "age":"23",
        "Address":"Chittoor",
        "city":"AP"
    },
    {
        "name":"Surya",
        "class":"4th",
        "age":"23",
        "Address":"Chittoor",
        "city":"AP"
    },
    {
        "name":"Surya",
        "class":"4th",
        "age":"23",
        "Address":"Chittoor",
        "city":"AP"
    },
    {
        "name":"Surya",
        "class":"4th",
        "age":"23",
        "Address":"Chittoor",
        "city":"AP"
    },
    {
        "name":"Surya",
        "class":"4th",
        "age":"23",
        "Address":"Chittoor",
        "city":"AP"
    },
    {
        "name":"Surya",
        "class":"4th",
        "age":"23",
        "Address":"Chittoor",
        "city":"AP"
    },
]