var worldContinent=[
    {
      Continent:"Asia",
      Countries:[
          "China",
          "India",
          "Indonesia",+
          "Pakistan",
          "Bangladesh",
          "Japan",
          "Philippines",
          "Vietnam",
          "Turkey",
          "Iran",
          "Thailand",
          "Myanmar",
          "South Korea",
          "Iraq",
          "Afghanisthan",
          "Saudi Arabia",
          "Udbekistan",
          "Malaysia",
          "Yemen",
          "Nepal",
          "North Korea",
          "Taiwan",
          "Sri Lanka",
          "Kazakhstan",
          "Syria",
          "Cambodia",
          "Jordan",
          "Azerbaijan",
          "United Arab Emirates",
          "Tajikistan",
          "Israel",
          "Hong Kong",
          "Laos",
          "Lebanon",
          "Kyrgyzstan",
          "Turkmenistan",
          "Singapore",
          "Oman",
          "State of Palestine",
          "Kuwait",
          "Georgia",
          "Mongolia",
          "Armenia",
          "Qatar",
          "Bahrain",
          "Timor-Leste",
          "Cypus",
          "Bhutan",
          "Macao",
          "Maldives",
          "Brunei Darussalam",
      ],
    },
    {
        Continent:"Africa",
        Countries:[
            "Nigeria",
            "Ethiopia",
            "Egypt",
            "Democratic Republic of the Congo",
            "Tanzania",
            "South Africa",
            "Kenya",
            "Uganda",
            "Algeria",
            "Sudan",
            "Morocco",
            "Angola",
            "Mozambique",
            "Ghana0",
            "Madagascar",
            "Cameroon",
            "Côte d'Ivoire",
            "Niger",
            "Burkina Faso",
            "Mali",
            "Malawi",
            "Zambia",
            "Senegal",
            "Chad",
            "Somalia",
            "Zimbabwe",	
            "Guinea",
            "Rwanda0",
            "Benin",
            "Burundi",
            "Tunisia",
            "South Sudan",
            "Togo",
            "Sierra Leone",
            "L,ibya",
            "Congo",
            "Liberia",
            "Central African Republic",
            "Mauritania",
            "Eritrea",
            "Namibia",
            "Gambia",
            "Botswana",
            "Gabon",
            "Lesotho",
            "Guinea-Bissau",
            "Equatorial Guinea",
            "Mauritius",
            "Eswatini",
            "Djibouti",
            "Réunion",
            "Comoros",
            "Western Sahara",
            "Cabo Verde",
            "Mayotte",
            "Sao Tome and Principe",
            "Seychelles",
            "Saint Helena",   
        ],
    },
    {
        Continent:"Europe",
        Countries:[
            "Russia",
            "Germany",
            "United Kingdom",
            "France",
            "Italy",
            "Spain",
            "Ukraine",
            "Poland",
            "Romania",
            "Netherlands",
            "Belgium",
            "Czechia",
            "Greece",
            "Portugal",
            "Sweden",
            "Hungary",
            "Belarus",
            "Austria",
            "Serbia",
            "Switzerland",
            "Bulgaria",
            "Denmark",
            "Finland",
            "Slovakia",
            "Norway",
            "Ireland",
            "Croatia",
            "Moldova",
            "Bosnia and Herzegovina",
            "Albania",
            "Lithuania",
            "North Macedonia",
            "Slovenia",
            "Latvia",
            "Estonia",
            "Montenegro",
            "Luxembourg",
            "Malta",
            "Iceland",
            "Channel Islands",
            "Isle of Man",
            "Andorra",
            "Faeroe Islands",
            "Monaco",   
            "Liechtenstein",   
            "San Marino",   
            "Gibraltar",  
            "Holy See",
        ],
    },
    {
        Continent:"North America",
        Countries:[
            "U.S.A.",
            "Mexico",
            "Canada",
            "Guatemala",
            "Haiti",
            "Cuba",
            "Dominican Republic",
            "Honduras",
            "Nicaragua",
            "El Salvador",
            "Costa Rica",
            "Panama",
            "Jamaica",
            "Puerto Rico",
            "Trinidad and Tobago",
            "Guadeloupe",
            "Belize",
            "Bahamas",
            "Martinique",
            "Barbados",
            "Saint Lucia",
            "Curaçao",
            "Grenada",
            "Saint Vincent and the Grenadines",
            "Aruba",
            "United States Virgin Islands",
            "Antigua and Barbuda",
            "Dominica",
            "Cayman Islands",
            "Bermuda",
            "Greenland",
            "Saint Kitts and Nevis",
            "Sint Maarten",
            "Turks and Caicos Islands",
            "Saint Martin",
            "British Virgin Islands",
            "Caribbean Netherlands",
            "Anguilla",
            "Saint Barthélemy",
            "Saint Pierre and Miquelon",
            "Montserrat",           				
        ],
    },
    {
        Continent:"South America",
        Countries:[   
            "Brazil",
            "Colombia",    
            "Argentina",  
            "Peru",   
            "Venezuela",
            "Chile",
            "Ecuador",
            "Bolivia",
            "Paraguay",
            "Uruguay",
            "Guyana",
            "Suriname",
            "French Guiana",
            "Falkland Islands",            	
        ],
    },
    {
        Continent:"Australia",
        Countries:[
            "Australia",
            "Papua New Guinea",
            "New Zealand",
            "Fiji",
            "Solomon Islands",
            "Micronesia",
            "Vanuatu",
            "New Caledonia",
            "French Polynesia",
            "Samoa",
            "Guam",
            "Kiribati",
            "Tonga",
            "Marshall Islands",
            "Northern Mariana Islands",
            "American Samoa",
            "Palau",
            "Cook Islands",
            "Tuvalu",
            "Wallis and Futuna Islands",
            "Nauru",
            "Niue",
            "Tokelau",            		
        ],
    },
];