var Actors=[
   {
    "Image":"https://images.livemint.com/rf/Image-621x414/LiveMint/Period2/2018/03/29/Photos/Processed/pawankalyan-kt1--621x414@LiveMint.jpg",
    "Name":"Pawan Kalyan",
    "DOB":"02/September/1971",
    "Age":"50 years",
    "Birth Place":"Baptla(AP)",
    "First Movie":"Akkada Ammayi Ikkada Abbayi",
   },
   {
    "Image":"https://assets.thehansindia.com/h-upload/2021/05/19/1600x960_1077045-ntr.jpg",
    "Name":"Jr.NTR",
    "DOB":"20/May/1983",
    "Age":"38 years",
    "Birth Place":"Hyderabad",
    "First Movie":"Ninnu Choodalani",
   },
   {
    "Image":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/RashmikaMandanna_at_Bheeshma_event.jpg/220px-RashmikaMandanna_at_Bheeshma_event.jpg",
    "Name":"Rashmika Mandanna",
    "DOB":"5/April/1996",
    "Age":"25 years",
    "Birth Place":"Virajpet(Karnataka)",
    "First Movie":"Chalo",
   },
   {
    "Image":"https://www.pinkvilla.com/imageresize/pooja_hegde_about_chiranjeevi_vijay.jpg?width=752&format=webp&t=pvorg",
    "Name":"Pooja Hegde",
    "DOB":"13/October/1990",
    "Age":"31 years",
    "BBirth Placeorn":"Bombay(Maharashtra)",
    "First Movie":"Oka Laila Kosam",
   },
   {
    "Image":"https://images.hindustantimes.com/img/2021/06/15/550x309/Mahesh_babu_1623759511516_1623759525940.jpg",
    "Name":"Mahesh Babu",
    "DOB":"9/August/1975",
    "Age":"46 years",
    "Birth Place":"Madras(Tamil Nadu)",
    "First Movie":"Rajakumarudu",
   },
   {
      "Image":"https://static.toiimg.com/thumb/88239805.cms?width=680&height=512&imgsize=35990",
      "Name":"Allu Arjun",
      "DOB":"8/April/1982",
      "Age":"39 years",
      "Birth Place":"Madras(Tamil Nadu)",
      "First Movie":"Gangotri",
     },
     {
      "Image":"https://www.breezemasti.com/wp-content/uploads/Anupama-Parameswaran-wiki-age-height-family-husband-movies.jpg",
      "Name":"Anupama Parameswaran",
      "DOB":"18/February/1996",
      "Age":"26 years",
      "Birth Place":"Irinjalakuda(Kerala)",
      "First Movie":"Premam",
     },
]