var food=[
    {
        Name:"Fruits",
        Types:[
            "Orange",
            "Apple",
            "Grapes",
            "Banana",
            "Watermelon",
            "Cherry",
            "Jack Fruit",
            "Straberry",
            "Avakoda",
            "blueberry",
            "Kiwi",
            "Ponogranet",
            "Dragon Fruit",
        ],
    },
    {
        Name:"Vegetables",
        Types:[
            "Brinjal",
            "tomato",
            "Ledies Fingers",
            "Potato",
            "Cabbage",
            "Cyaly Flower",
            "Beans",
            "Curry Lieves",
            "Corriander Lieves",
            "Methi Lieves",
            "Carrot",
            "Beatroot",
            "Drum Stick",
        ],
    },
    {
        Name:"Sweets",
        Types:[
            "Laddu",
            "Carrot Halwa",
            "Kaju Katli",
            "Gulab Jamun",
            "jalebi",
            "Rava Laddu",
            "Kheer/Payasam",
            "Rasmalai",
            "Kova Jangri",
            "Mysorepak",
            "Milk Kova",
            "Badusha",
        ],
    },
    {
        Name:"Curries",
        Types:[
            "Sambar",
            "Vegetable Kurma",
            "Chicken Tikka",
            "Rasam",
            "Egg Curry",
            "Motten Manchuria",
            "Paya",
            "Chicken curry",
            "Moong Daal",
        ],
    },
    {
        Name:"Juice",
        Types:[
            "Spraite",
            "Thumsup",
            "Fanta",
            "Coca Cola",
            "Mountain Dew",
            "Mirinda",
            "7 up",
            "Pepsi",
            "Lemon Juice",
        ],
    },
    {
        Name:"Hot Drinks",
        Types:[
            "Tea",
            "Coffee",
            "Milk",
            "Gurliks",
            "Boost",
            "Badam Milk",
            "Black Coffe",
        ],
    },
    {
        Name:"Ice Creams",
        Types:[
            "Chaco Bar",
            "Venila",
            "Cone",
            "Mutka Ice",
            "Kulfi",
            "Cup Ice Cream",
            "Butter Scotch",
        ],
    },
    {
        Name:"Biryani",
        Types:[
            "Chicken Biryani",
            "Mutton Biryani",
            "Egg Biryani",
            "vegetabla Biryani",
            "Mandi Biryani",
        ],
    },
]