var subject = [
    {
        flowers: "flowers",
        names: [
            "Rose",
            "Lilly",
            "Lotus",
            "Chamanthi",
            "Gundumalli",
            "Josemin",
            "sunflower",
            "dairy",
        ],
    },
    {
        flowers: "fruits",
        names: [
            "Apple",
            "Manago",
            "Graps",
            "Staberry",
            "Gova",
            "Sapota",
            "Banana",
            "Pupayya",
        ],
    },
    {
        flowers: "Vehicals",
        names: [
            "Car",
            "Larry",
            "Bus",
            "Scooter",
            "Cycle",
            "Train",
            "JCB",
            "Tracter",
        ],
    },
    {
        flowers: "Criket Players",
        names: [
            "Dhoni",
            "Virat Kohili",
            "Surya Yadav",
            "sampath",
            "Gundumani",
            "Joseph",
            "manglii",
            "simhaaa",
        ],
    },
    {
        flowers: "Friends",
        names: [
            "Raju",
            "Deena",
            "Rehaman",
            "Sadik",
            "Surya",
            "SaiKiran",
            "Magesh",
            "Lokesh",
            "Harish",
        ],
    },
    {
        flowers: "My family",
        names: [
            "sruthi",
            "surya",
            "vishal",
            "raghu",
            "selvi",
            "balaji",
            "durga",
            "asha",
        ],
    },
    {
        flowers: "Games",
        names: [
            "Football",
            "Criket",
            "Vallyball",
            "hockey",
            "basketball",
            "Kabadi",
            "chess",
            "caroomboard",
        ],
    },
    {
        flowers: "Sweets",
        names: [
            "Laddu",
            "Gelabbi",
            "palgova",
            "golab jam",
            "sweet",
            "boomdhi",
            "chakkara",
            "belam",
        ],
    },
    {
        flowers: "foods",
        names: [
            "goobi rice",
            "egg rice",
            "masala rice",
            "oil rice",
            "fryed rice",
            "chiken rice",
            "biriyani",
            "white rice"
        ],
    },
    {
        flowers: "Juices",
        names: [
            "lemon juice",
            "fruit juice",
            "badham juice",
            "rose juice",
            "sugarcan juice",
            "pistha juice",
            "mango juice",
            "apple juice",
        ],
    },
    {
        flowers: "flowers",
        names: [
            "Rose",
            "Lilly",
            "Lotus",
            "Chamanthi",
            "Gundumalli",
            "Josemin",
            "sunflower",
            "dairy",
        ],
    },
    {
        flowers: "flowers",
        names: [
            "Rose",
            "Lilly",
            "Lotus",
            "Chamanthi",
            "Gundumalli",
            "Josemin",
            "sunflower",
            "dairy"
        ],
    },
    {
        flowers: "flowers",
        names: [
            "Rose",
            "Lilly",
            "Lotus",
            "Chamanthi",
            "Gundumalli",
            "Josemin",
            "sunflower",
            "dairy"
        ],
    },
    {
        flowers: "flowers",
        names: [
            "Rose",
            "Lilly",
            "Lotus",
            "Chamanthi",
            "Gundumalli",
            "Josemin",
            "sunflower",
            "dairy"
        ],
    },
    {
        flowers: "flowers",
        names: [
            "Rose",
            "Lilly",
            "Lotus",
            "Chamanthi",
            "Gundumalli",
            "Josemin",
            "sunflower",
            "dairy"
        ],
    },
];