var FilmActors = [
    {
        Actor: "Chiranjivi",
        Information: [
            "Birth Name : Konidela Siva Sankara Vara Prasad",
            "DOB : 22 August 1955",
            "Age : 66 years",
            "Birth Place : Mogalthur (Andhra Pradesh)",
            "Relatives : Allu-Konidela family",
            "Residence : Jubilee Hills,Hyderabad,Telangana",
            "Occupation : Film actor,dancer,politician and television host",
            "Awards : Padma Bhushan (2006)",
            "Nickname : Megastar",
        ],
    },
    {
        Actor: "Pawan Kalyan",
        Information: [
            "Birth Name : Konidela Kalyan Babu",
            "DOB : 2 September 1968",
            "Age : 53 years",
            "Birth Place : Bapatla (Andhra Pradesh)",
            "Political party : Jana Sena Party",
            "Relatives : Allu-Konidela family",
            "Occupation : Actor,writer,Film Producer,Politician,Director,Choreographer,Stunt director and Singer",
        ],
    },
    {
        Actor: "Mahesh Babu",
        Information: [
            "Birth Name : Ghattamaneni Mahesh Babu",
            "DOB : 9 August 1975",
            "Age : 46 years",
            "Birth Place : Madras (Tamil Nadu)",
            "Occupation : Film actor",
            "Spouse : Namrata Shirodkar",
            "Children : 2",
        ],
    },
    {
        Actor: "Prabhas",
        Information: [
            "Birth Name : Uppalapati Venkata Suryanarayana Prabhas Raju",
            "DOB : 23 October 1979",
            "Age : 42 years",
            "Birth Place : Madras (Tamil Nadu)",
            "Occupation : Actor",
            "Parents : Uppalapati Surya Narayana Raju (father)",
            "Relatives : Krishnam Raju (uncle)",
        ],
    },
    {
        Actor: "Dhanush",
        Information: [
            "Birth Name : Venkatesh Prabhu Kasthuri Raja",
            "DOB : 28 July 1983",
            "Age : 38 years",
            "Birth Place :  Madras (Tamil Nadu)",
            "Occupation : Actor,director,producer,playback singer and lyricist",
            "Spouse : Aishwarya Rajinikanth",
            "Parents : Kasthuri Raja (father)",
            "Relatives : Kasthuri Raja family",
        ],
    },
    {
        Actor: "Vijay",
        Information: [
            "Birth Name : Joseph Vijay Chandrasekhar",
            "DOB : 22 June 1974",
            "Age : 47 years",
            "Birth Place : Madras (Tamil Nadu)",
            "Occupation : Actor,dancer,playback singer and philanthropist",
            "Spouse : Sangeeta Sornalingam",
            "Children : 2",
            "Parents : S. A. Chandrasekhar (father)",
            "Relatives : Chandrasekhar family",
        ],
    },
    {
        Actor: "Sid Sriram",
        Information: [
            "Birth Name : Sidharth Sriram",
            "DOB : 19 May 1990",
            "Age : 31 years",
            "Birth Place :  Chennai (Tamil Nadu)",
            "Origin : Indian-American",
            "Genres : R&B, Carnatic",
            "Occupation : Carnatic musician,Music producer and Playback singer",
        ],
    },
    {
        Actor: "Rajinikanth",
        Information: [
            "Birth Name : Shivaji Rao Gaekwad",
            "DOB : 12 December 1950",
            "Age : 71 years",
            "Birth Place : Bangalore (Mysore)",
            "Occupation : Actorfilm producer",
            "Spouse : Latha Rajinikanth",
            "Children : Aishwarya and Soundarya",
            "Awards : Dadasaheb Phalke Award (2020),Padma Vibhushan (2016),NTR National Award (2016),Padma Bhushan (2000) and Kalaimamani (1984)",
        ],
    },
];