var students=[
    {
        "name":"deena",
        "class":"2nd",
        "group":"b.com",
        "gender":"male",
        "address":"chittoor",
        "city":"chittoor",
        "pin code":"5171001",
        "sign":"deena",        
    },
    {
        "name":"raju",
        "class":"3rd",
        "group":"bzc",
        "gender":"male",
        "address":"Gvk",
        "city":"chittoor",
        "pin code":"517178",
        "sign":"raju",        
    },
    {
        "name":"surya",
        "class":"4th",
        "group":"b.gen",
        "gender":"male",
        "address":"gd nellore",
        "city":"chittoor",
        "pin code":"51798",
        "sign":"surya prakash",        
    },
    {
        "name":"sai",
        "class":"5th",
        "group":"BA",
        "gender":"male",
        "address":"pysics",
        "city":"chittoor",
        "pin code":"876890",
        "sign":"saikiran",        
    },
    {
        "name":"mahesh",
        "class":"6th",
        "group":"mba",
        "gender":"male",
        "address":"dahrag",
        "city":"chittoor",
        "pin code":"456789",
        "sign":"mahesh",        
    },
    {
        "name":"mah",
        "class":"7th",
        "group":"mca",
        "gender":"female",
        "address":"donang",
        "city":"chittoor",
        "pin code":"456788",
        "sign":"maha",        
    },
    {
        "name":"lokesh",
        "class":"8th",
        "group":"mcom",
        "gender":"male",
        "address":"bangarampalam",
        "city":"chittoor",
        "pin code":"345678",
        "sign":"lokesh",        
    },
    {
        "name":"harish",
        "class":"9th",
        "group":"bzc",
        "gender":"male",
        "address":"pardharami",
        "city":"chittoor",
        "pin code":"567890",
        "sign":"harish",        
    },
    {
        "name":"sandeep",
        "class":"10th",
        "group":"gnm",
        "gender":"male",
        "address":"london",
        "city":"england",
        "pin code":"234445",
        "sign":"sandeep",        
    },
    {
        "name":"dileep",
        "class":"11th",
        "group":"dlm",
        "gender":"male",
        "address":"chittoor",
        "city":"chitoor",
        "pin code":"234567",
        "sign":"dileep",        
    },
    {
        "name":"saranya",
        "class":"b.tech",
        "group":" english",
        "gender":"female",
        "address":"vepana palli",
        "city":"chittoor",
        "pin code":"345342",
        "sign":"saroja",        
    },
]